"""Benchmark support: consistent timing, precision checks and plot styling.

Re-exported here is the harness every benchmark uses. Single-investigation modules
(``analysis.abtest``, ``analysis.admissibility``, ``analysis.loss_gap``,
``model.flops_analytic``, ``vendor.*``) are reached by their own module path.

Importing this module pulls in matplotlib; the training path never touches it.
See docs/performance/benchmarking.md.
"""

from kohakuwullm.bench.analysis.runlog import (
    contended_fraction,
    discover_lr_multipliers,
    is_exclusive,
    load_arms,
    load_run,
    pair_speedups,
    replay_identical,
    speedup,
    spike_steps,
    step_diffs_ms,
    step_ms,
    write_step_rows,
)
from kohakuwullm.bench.analysis.sweep import (
    best_cell,
    classify,
    falling_throughput,
    load_sweep,
    ordered_presets,
    parse_tag,
    planning_units,
    resolve_dtype,
    strategy_coverage,
)
from kohakuwullm.bench.core.batches import (
    make_info,
    make_packs,
    make_tokens,
    trained_tokens,
)
from kohakuwullm.bench.core.contention import (
    contended_fraction_limit,
    contended_fraction_min_iters,
    sample_contended_fraction,
    sample_spread,
    spread_has_power,
    spread_no_power_below_ms,
    spread_threshold,
)
from kohakuwullm.bench.core.plotting import (
    Palette,
    bar_labels,
    finish_axis,
    new_figure,
    save_figure,
)
from kohakuwullm.bench.core.timing import (
    bench_ms,
    bench_peak_memory,
    bench_samples,
    cached_peak_bandwidth,
    cpu_enqueue_ms,
    device_name,
    device_op_counts,
    format_metrics,
    graph_ms,
    measure_peak_bandwidth,
    module_metrics,
    rel_error,
    stream_bandwidths,
    theoretical_bandwidth_gbps,
    timing_profile,
    ulp_error,
)
from kohakuwullm.bench.model.ladder import RungCensus, census, ladder_census

__all__ = [
    "RungCensus",
    "census",
    "ladder_census",
    "Palette",
    "bar_labels",
    "finish_axis",
    "new_figure",
    "save_figure",
    "make_info",
    "make_packs",
    "make_tokens",
    "trained_tokens",
    "contended_fraction",
    "discover_lr_multipliers",
    "is_exclusive",
    "load_arms",
    "load_run",
    "pair_speedups",
    "replay_identical",
    "speedup",
    "spike_steps",
    "step_diffs_ms",
    "step_ms",
    "write_step_rows",
    "bench_ms",
    "bench_samples",
    "bench_peak_memory",
    "cached_peak_bandwidth",
    "cpu_enqueue_ms",
    "device_op_counts",
    "format_metrics",
    "graph_ms",
    "module_metrics",
    "device_name",
    "measure_peak_bandwidth",
    "sample_contended_fraction",
    "sample_spread",
    "contended_fraction_limit",
    "contended_fraction_min_iters",
    "spread_has_power",
    "spread_no_power_below_ms",
    "spread_threshold",
    "stream_bandwidths",
    "theoretical_bandwidth_gbps",
    "timing_profile",
    "rel_error",
    "ulp_error",
    "best_cell",
    "classify",
    "falling_throughput",
    "load_sweep",
    "planning_units",
    "ordered_presets",
    "parse_tag",
    "resolve_dtype",
    "strategy_coverage",
]
